//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.03 at 04:24:07 PM EEST 
//


package com.github.yuri0x7c1.ofbiz.explorer.service.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}fail-message"/>
 *         &lt;element ref="{}fail-property"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{}attlist.type-validate"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "failMessage",
    "failProperty"
})
@XmlRootElement(name = "type-validate")
public class TypeValidate {

    @XmlElement(name = "fail-message")
    protected FailMessage failMessage;
    @XmlElement(name = "fail-property")
    protected FailProperty failProperty;
    @XmlAttribute(name = "method")
    protected String method;
    @XmlAttribute(name = "class")
    protected String clazz;

    /**
     * Gets the value of the failMessage property.
     * 
     * @return
     *     possible object is
     *     {@link FailMessage }
     *     
     */
    public FailMessage getFailMessage() {
        return failMessage;
    }

    /**
     * Sets the value of the failMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link FailMessage }
     *     
     */
    public void setFailMessage(FailMessage value) {
        this.failMessage = value;
    }

    /**
     * Gets the value of the failProperty property.
     * 
     * @return
     *     possible object is
     *     {@link FailProperty }
     *     
     */
    public FailProperty getFailProperty() {
        return failProperty;
    }

    /**
     * Sets the value of the failProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link FailProperty }
     *     
     */
    public void setFailProperty(FailProperty value) {
        this.failProperty = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        if (clazz == null) {
            return "org.apache.ofbiz.base.util.UtilValidate";
        } else {
            return clazz;
        }
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

}
