//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.17 at 02:28:17 PM EEST 
//


package com.github.yuri0x7c1.ofbiz.explorer.entity.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aggregate-function.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="aggregate-function">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="min"/>
 *     &lt;enumeration value="max"/>
 *     &lt;enumeration value="sum"/>
 *     &lt;enumeration value="avg"/>
 *     &lt;enumeration value="count"/>
 *     &lt;enumeration value="count-distinct"/>
 *     &lt;enumeration value="upper"/>
 *     &lt;enumeration value="lower"/>
 *     &lt;enumeration value="extract-year"/>
 *     &lt;enumeration value="extract-month"/>
 *     &lt;enumeration value="extract-day"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "aggregate-function")
@XmlEnum
public enum AggregateFunction {

    @XmlEnumValue("min")
    MIN("min"),
    @XmlEnumValue("max")
    MAX("max"),
    @XmlEnumValue("sum")
    SUM("sum"),
    @XmlEnumValue("avg")
    AVG("avg"),
    @XmlEnumValue("count")
    COUNT("count"),
    @XmlEnumValue("count-distinct")
    COUNT_DISTINCT("count-distinct"),
    @XmlEnumValue("upper")
    UPPER("upper"),
    @XmlEnumValue("lower")
    LOWER("lower"),
    @XmlEnumValue("extract-year")
    EXTRACT_YEAR("extract-year"),
    @XmlEnumValue("extract-month")
    EXTRACT_MONTH("extract-month"),
    @XmlEnumValue("extract-day")
    EXTRACT_DAY("extract-day");
    private final String value;

    AggregateFunction(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AggregateFunction fromValue(String v) {
        for (AggregateFunction c: AggregateFunction.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
